language: ruby
cache: bundler
os:
- linux
- osx
rvm:
- 2.6
- 2.5
- 2.4
- ruby-head
before_install:
- curl -L https://cpanmin.us | perl - --sudo App::cpanminus
- sudo cpanm --notest LaTeXML@0.8.4
- curl -L https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/travis.sh | bash
- gem install bundler -v 2.0.1
- bundle update
matrix:
  allow_failures:
    - rvm: ruby-head

