dist: trusty
sudo: false
language: ruby
rvm:
  - 2.5
  - 2.4
  - 2.3
  - ruby-head
before_install:
  - gem install bundler -v 1.16.1
  - unset _JAVA_OPTIONS
  - wget "http://downloads.sourceforge.net/project/plantuml/plantuml.jar?r=&ts=1424308684&use_mirror=jaist" -O plantuml.jar
  - sudo mkdir -p /opt/plantuml
  - sudo cp plantuml.jar /opt/plantuml
  - echo "#! /bin/sh" > plantuml.sh
  - echo 'exec java -jar /opt/plantuml/plantuml.jar "$@"' >> plantuml.sh
  - sudo install -m 755 -D plantuml.sh /usr/bin/plantuml
  - plantuml -version
  - sudo apt-get install latexml
matrix:
  allow_failures:
    - rvm: ruby-head
