dist: trusty
sudo: false
language: ruby
rvm:
  - 2.5
  - 2.4
  - 2.3
  - ruby-head
before_install:
  - gem install bundler -v 2.0.1
  - curl -sSL https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | sudo bash -s
matrix:
  allow_failures:
    - rvm: ruby-head
