language: ruby
cache: bundler
os:
- linux
- osx
rvm:
- 2.5
- 2.4
- ruby-head
before_install:
- gem install bundler -v 2.0.1
- bundle update
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash -c "apt-get update && curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash" ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb ; fi
matrix:
  allow_failures:
    - rvm: ruby-head

