= Metanorma-standoc

image:https://img.shields.io/gem/v/metanorma-standoc.svg["Gem Version", link="https://rubygems.org/gems/metanorma-standoc"]
image:https://github.com/metanorma/metanorma-standoc/workflows/macos/badge.svg["Build Status (macOS)", link="https://github.com/metanorma/metanorma-standoc/actions?workflow=macos"]
image:https://github.com/metanorma/metanorma-standoc/workflows/ubuntu/badge.svg["Build Status (ubuntu)", link="https://github.com/metanorma/metanorma-standoc/actions?workflow=ubuntu"]
image:https://github.com/metanorma/metanorma-standoc/workflows/windows/badge.svg["Build Status (Windows)", link="https://github.com/metanorma/metanorma-standoc/actions?workflow=windows"]
image:https://codeclimate.com/github/metanorma/metanorma-standoc/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/metanorma/metanorma-standoc"]
image:https://img.shields.io/github/issues-pr-raw/metanorma/metanorma-standoc.svg["Pull Requests", link="https://github.com/metanorma/metanorma-standoc/pulls"]
image:https://img.shields.io/github/commits-since/metanorma/metanorma-standoc/latest.svg["Commits since latest",link="https://github.com/metanorma/metanorma-standoc/releases"]

Gem for serialising the https://github.com/metanorma/metanorma-model-standoc[Metanorma Standoc] model. 

== Functionality

This gem processes Metanorma documents following a template for generating standards documents, according
to a range of standards classes. This gem provides underlying generic functionality; behaviour specific
to each standards class is refined in the gem specific to that standards class (e.g. https://github.com/metanorma/metanorma-iso).
The following outputs are generated.

* Metanorma XML representation of the document, intended as a document model for 
Standards. The Metanorma XML representation is processed in turn, to generate one or more of 
the following outputs as end deliverables, depending on each standards class gem:
* Microsoft Word output (`.doc`)
* HTML output (`.html`)
* PDF (`.pdf`)

The following input formats are supported:

* http://asciidoctor.org/[Asciidoctor]

This README provides an overview of the functionality of the gem; see also
https://github.com/metanorma/metanorma-iso/blob/master/docs/guidance.adoc[Guidance for authoring].
https://github.com/metanorma/metanorma-iso/blob/master/docs/quickstart.adoc[Quickstart guide]
gives a summary overview.

NOTE: http://asciimath.org[AsciiMathML] is used for mathematical formatting.
The gem uses the https://github.com/asciidoctor/asciimath[Ruby AsciiMath parser],
which is syntactically stricter than the common MathJax processor;
if you do not get expected results, try bracketting terms your in AsciiMathML
expressions.

=== Installation

If you are using a Mac, the https://github.com/metanorma/metanorma-macos-setup
repository has instructions on setting up your machine to run Metanorma
scripts such as this one. You need only run the following in a Terminal console:

[source,console]
----
$ bash <(curl -s https://raw.githubusercontent.com/metanorma/metanorma-macos-setup/master/metanorma-setup)
$ gem install metanorma-standoc
$ gem install metanorma-cli 
----

The metanorma-cli gem is the command-line interface for the Metanorma tool suite
(incorporating the `metanorma` executable seen above).

== Documentation

See http://metanorma.com[]

