= Metanorma-standoc

image:https://img.shields.io/gem/v/metanorma-standoc.svg["Gem Version", link="https://rubygems.org/gems/metanorma-standoc"]
image:https://github.com/metanorma/metanorma-standoc/workflows/rake/badge.svg["Build Status", link="https://github.com/metanorma/metanorma-standoc/actions?workflow=rake"]
image:https://codeclimate.com/github/metanorma/metanorma-standoc/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/metanorma/metanorma-standoc"]
image:https://img.shields.io/github/issues-pr-raw/metanorma/metanorma-standoc.svg["Pull Requests", link="https://github.com/metanorma/metanorma-standoc/pulls"]
image:https://img.shields.io/github/commits-since/metanorma/metanorma-standoc/latest.svg["Commits since latest",link="https://github.com/metanorma/metanorma-standoc/releases"]

Gem for serialising the https://github.com/metanorma/metanorma-model-standoc[Metanorma Standoc] model. 

== Functionality

This gem processes Metanorma AsciiDoc input into the Metanorma document model.
This gem provides underlying generic functionality; behaviour specific
to each standards class is refined in the gem specific to that standards class
(e.g. https://github.com/metanorma/metanorma-iso[Metanorma ISO]).

The following outputs are generated:

* Metanorma semantic XML
* Metanorma presentation XML

These Metanorma XML representations are processed downstream by the `isodoc` gem
to generate other end deliverables, depending on each standards class.

The following input formats are supported:

* Metanorma AsciiDoc

See the https://www.metanorma.org[Metanorma website] for more information.

NOTE: http://asciimath.org[AsciiMathML] is used for mathematical formatting.
The gem uses the https://github.com/asciidoctor/asciimath[Ruby AsciiMath parser],
which is syntactically stricter than the common MathJax processor;
if you do not get expected results, try bracketting terms your in AsciiMathML
expressions.

=== Installation

See the https://www.metanorma.org[Metanorma website] for instructions.

In the terminal:

[source,console]
----
$ gem install metanorma-standoc
$ gem install metanorma-cli 
----

`metanorma-cli` is the command-line interface for the Metanorma suite
(incorporating the `metanorma` executable seen above).

== Documentation

See the https://www.metanorma.org[Metanorma website] for details.
