module Metanorma
  module Standoc
    class Converter
      # rubocop:disable Naming/VariableNumber
      STANDOC_LOG_MESSAGES = {
        "STANDOC_1": { category: "Include",
                       error: "Specified boilerplate file does not exist: %s",
                       severity: 0 },
        "STANDOC_2": { category: "Table", error: "Empty table",
                       severity: 0 },
        "STANDOC_3": { category: "Crossreferences",
                       error: "invalid index \"%s\" cross-reference: " \
                       "wrong number of attributes in `index:%s[%s]`",
                       severity: 0 },
        "STANDOC_4": { category: "Table",
                       error: "Table rows in table %s: check rowspan",
                       severity: 0 },
        "STANDOC_5": { category: "Table",
                       error: "Table exceeds maximum number of columns defined (%s)",
                       severity: 0 },
        "STANDOC_6": { category: "Maths",
                       error: "Malformed MathML: %s\n%s",
                       severity: 0 },
        "STANDOC_7": { category: "Metanorma XML Syntax", error: "%s",
                       severity: 2 },
        "STANDOC_8": { category: "Anchors", error: "Malformed URI: %s",
                       severity: 0 },
        "STANDOC_9": { category: "Bibliography",
                       error: "Attachment %s does not exist",
                       severity: 0 },
        "STANDOC_10": { category: "Anchors",
                        error: "The following reference is missing an anchor:\n%s",
                        severity: 1 },
        "STANDOC_11": { category: "Bibliography",
                        error: "Reference %s is missing a title",
                        severity: 1 },
        "STANDOC_12": { category: "Bibliography",
                        error: "Reference %s is missing a document identifier (docid)",
                        severity: 1 },
        "STANDOC_13": { category: "AsciiDoc Input",
                        error: "term reference not in expected format:%s",
                        severity: 1 },
        "STANDOC_14": { category: "Style",
                        error: "Style override set for ordered list",
                        severity: 2 },
        "STANDOC_15": { category: "Crossreferences",
                        error: "Could not resolve footnoteblock:[%s]",
                        severity: 1 },
        "STANDOC_16": { category: "AsciiDoc Input",
                        error: "Section not marked up as [bibliography]!",
                        severity: 2 },
        "STANDOC_17": { category: "Bibliography",
                        error: "ERROR: No document identifier retrieved for %s",
                        severity: 2 },
        "STANDOC_18": { category: "Bibliography",
                        error: "ERROR: No title retrieved for %s", severity: 2 },
        "STANDOC_19": { category: "Bibliography",
                        error: "Cannot find reference %s for local Relaton " \
                                "data source %s", severity: 0 },
        "STANDOC_20": { category: "AsciiDoc Input",
                        error: "Metadata definition list does not follow a term designation",
                        severity: 2 },
        "STANDOC_21": { category: "Terms",
                        error: "Removed duplicate designation %s",
                        severity: 2 },
        "STANDOC_22": { category: "Bibliography",
                        error: "Term \"%s\" does not match IEV %s \"%s\"",
                        severity: 1 },
        "STANDOC_23": { category: "Anchors",
                        error: "Concept cross-reference error: %s",
                        severity: 0 },
        "STANDOC_24": { category: "Terms",
                        error: "Term %s occurs twice as preferred designation: %s",
                        severity: 1 },
        "STANDOC_25": { category: "Terms", severity: 0,
                        error: <<~ERROR.freeze },
                          Clause not recognised as a term clause, but contains designation markup
                           (<code>preferred:[], admitted:[], alt:[], deprecated:[]</code>):<br/>
                          %s</br>
                          Ensure the parent clause is recognised as a terms clause by inserting <code>[heading=terms and definitions]</code> above the title,
                          in case the heading is not automatically recognised. See also <a href="https://www.metanorma.org/author/topics/sections/concepts/#clause-title">Metanorma documentation</a>.
                        ERROR
        "STANDOC_26": { category: "AsciiDoc Input",
                        error: "Error: Symbol reference in `symbol[%s]` missing: \"%s\" is not defined in document",
                        severity: 1 },
        "STANDOC_27": { category: "AsciiDoc Input",
                        error: "Error: Term reference to `%s` missing: \"%s\" is not defined in document%s",
                        severity: 1 },
        "STANDOC_28": { category: "Crossreferences",
                        error: "term source %s not referenced",
                        severity: 1 },
        "STANDOC_29": { category: "AsciiDoc Input",
                        error: "converter missing for %s node in Metanorma backend",
                        severity: 1 },
        "STANDOC_30": { category: "Crossreferences",
                        error: "%s does not have a corresponding anchor ID in the bibliography!",
                        severity: 2 },
        "STANDOC_31": { category: "Crossreferences",
                        error: "Illegal cross-reference connective: %s",
                        severity: 0 },
        "STANDOC_32": { category: "Crossreferences",
                        error: "%s does not have a corresponding anchor ID in the bibliography!",
                        severity: 2 },
        "STANDOC_33": { category: "Maths",
                        error: "Invalid MathML: %s\n %s%s",
                        severity: 0 },
        "STANDOC_34": { category: "Style",
                        error: "There is an instance of %s nested within %s",
                        severity: 2 },
        "STANDOC_35": { category: "Style",
                        error: "There is a crossreference to an instance of %s nested within %s: %s",
                        severity: 2 },
        "STANDOC_36": { category: "Anchors",
                        error: "ID %s has already been used at line %s",
                        severity: 0 },
        "STANDOC_37": { category: "Bibliography",
                        error: "Cannot process format %s for local Relaton data source %s",
                        severity: 0 },
        "STANDOC_38": { category: "Anchors",
                        error: "Crossreference target %s is undefined",
                        severity: 1 },
        "STANDOC_39": { category: "Blocks",
                        error: "%s is empty",
                        severity: 1 },
        "STANDOC_40": { category: "Bibliography",
                        error: "Could not retrieve %s: no access to online site",
                        severity: 1 },
        "STANDOC_41": { category: "Include",
                        error: "Unresolved directive %s",
                        severity: 0 },
        "STANDOC_42": { category: "Metanorma XML Syntax",
                        error: "Invalid passthrough content: %s\n" \
                      "This is not valid Metanorma XML. If you intended a different format, such as HTML, you need to specify `format=` on the pass markup;\n" \
                      "refer to https://www.metanorma.org/author/topics/blocks/passthroughs/",
                        severity: 0 },
        "STANDOC_43": { category: "AsciiDoc Input",
                        error: <<~REF.freeze, severity: 1 },
                          no anchor on reference, markup may be malformed: see
                          https://www.metanorma.org/author/topics/sections/bibliography/ ,
                          https://www.metanorma.org/author/iso/topics/markup/#bibliographies : %s
                        REF
        "STANDOC_44": { category: "Images", error: "Image not found: %s",
                        severity: 0 },
        "STANDOC_45": { category: "Images",
                        error: "Corrupt PNG image detected: %s",
                        severity: 2 },
        "STANDOC_46": { category: "Images",
                        error: "Image too large for Data URI encoding: disable Data URI encoding (`:data-uri-image: false`), or set `:data-uri-maxsize: 0`",
                        severity: 0 },
        "STANDOC_47": { category: "Crossreferences",
                        error: "mismatch of callouts (%s) and annotations (%s)",
                        severity: 0 },
        "STANDOC_48": { category: "Style", error: "(generic warning) %s",
                        severity: 2 },
        "STANDOC_49": { category: "Bibliography",
                        error: "Numeric reference in normative references",
                        severity: 1 },
        "STANDOC_50": { category: "Fatal Error", error: "%s", severity: 0 },
        "STANDOC_51": { category: "Maths",
                        error: "latexmlmath failed to process equation:\n%s",
                        severity: 1 },
        "STANDOC_52": { category: "Bibliography",
                        error: "Bibliographic spans: %s",
                        severity: 0 },
        "STANDOC_53": { category: "Bibliography",
                        error: "Bibliographic spans: %s",
                        severity: 1 },
        "STANDOC_54": { category: "Bibliography",
                        error: "Cannot process file %s for local Relaton data source %s",
                        severity: 0 },
        "STANDOC_55": { category: "Images",
                        error: "Corrupt SVG image detected, error found: %s %s%s%s",
                        severity: 2 },
        "STANDOC_56": { category: "Images",
                        error: "Corrupt SVG image detected, could not be fixed: %s %s%s%s",
                        severity: 1 },
        "STANDOC_57": { category: "Images",
                        error: "SVG image warning: %s %s%s%s",
                        severity: 3 },
        "STANDOC_58": { category: "Images",
                        error: "Corrupt SVG image detected, fix attempted: %s %s: %s %s, Node: %s",
                        severity: 2 },
        "STANDOC_59": { category: "Images",
                        error: "SVG unresolved internal reference: %s line %s",
                        severity: 3 },
        "STANDOC_60": { category: "Bibliography",
                        error: "Unrecognised bibliographic style: %s",
                        severity: 1 },
        "RELATON_1": { category: "Relaton",
                       error: "(Error from Relaton) %s",
                       severity: 0 },
        "RELATON_2": { category: "Relaton",
                       error: "(Error from Relaton) %s",
                       severity: 1 },
        "RELATON_3": { category: "Relaton",
                       error: "(Error from Relaton) %s",
                       severity: 2 },
        "RELATON_4": { category: "Relaton",
                       error: "(Error from Relaton) %s",
                       severity: 3 },
        "RELATON_5": { category: "Relaton",
                       error: "(Error from Relaton IEV) %s",
                       severity: 0 },

      }.freeze
      # rubocop:enable Naming/VariableNumber

      def log_messages
        STANDOC_LOG_MESSAGES
      end
    end
  end
end
