# frozen_string_literal: true

module Metanorma
  module StandardDocument
    module Refs
      # Casing of the autogenerated label of a cross-reference.
      class XrefCaseType < Lutaml::Model::Serializable
        attribute :value, :string

        attribute :semx_id, :string
        attribute :original_id, :string

        def self.values
          %w[capital lowercase]
        end

        xml do
          element "xref-case-type"
          map_content to: :value

          map_attribute "semx-id", to: :semx_id
          map_attribute "original-id", to: :original_id
        end
      end
    end
  end
end
