name: rake

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  rake:
    uses: metanorma/ci/.github/workflows/plantuml-rake.yml@main
    secrets:
      pat_token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
