name: rake

on:
  push:
    branches: [ master, main ]
  pull_request:

permissions:
  contents: write

jobs:
  rake:
    uses: metanorma/ci/.github/workflows/inkscape-rake.yml@main
    secrets:
      pat_token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
